### Linear Algebra
Linear algerba is a branch of mathematics essential for understanding and working with machine learning algorithms. Some key concepts from linear algebra useful for deep learning concepts include scalars, vectors, matrices, and tensors, multiplying matrices, identity and inverse matrices, linear dependence, span, norms, eigendecomposition, singular value decomposition, etc.

In this notebook, I will code some of the more applied linear algebra techniques such as various types of norms, eigendeomposition, singular value decomposition, and principal component analysis. Many of these techniques have a prewritten numpy or other library function to compute them, but for learning purposes we will recreate them using some of the simpler numpy functionality.


In [1]:
import numpy as np

### Norms
Norms are denoted as L<sup>p</sup> and include some of the following:
* Euclidean (L<sup>2</sup>)
* L<sup>1</sup>
* Max norm
* Frobenius norm

#### Euclidean Norm and other L<sup>p</sup> norms
Euclidean norm is the distance between the origin and point identified as x, denoted as L<sup>2</sup>. The L<sup>2</sup> norm is very common and often referred to as ||x||. It is also common to measure the size of a vector using the squared L<sup>2</sup> norm, which is also just x<sup>T</sup>x.

In [2]:
x = np.array([2.5,-4.8,1.2])
p = 2
norm = sum(abs(x)**p)**(1/p)
print(f"L{p} norm has size of {norm}")

L2 norm has size of 5.543464620614079


Functionalize the Norm calculation

In [3]:
def norm(x,p=2):
    assert p >=1, "p must be greater than or equal to 1"
    
    return np.sum(abs(x)**p)**(1/p)

print(norm(x))

5.543464620614079


Three ways to calculate squared L<sup>2</sup> norm shown below

In [4]:
print(norm(x)**2)
print(x.T.dot(x))
print(sum(x.T*x))

30.73
30.73
30.73


#### Max Norm
Simplifies to the absolute value of the element with the largest magnitude of the vector.

In [5]:
x = np.array([2.5,-4.8,1.2])

print(f"The Max norm of the vector {x} is {max(abs(x))}")



The Max norm of the vector [ 2.5 -4.8  1.2] is 4.8


#### Frobenius Norm
Most common way to measure the size of a matrix in the context of deep learning is with the Frobenius norm, which is anagolous to the L<sup>2</sup> norm of a vector.

In [6]:
A = np.array([[6.7,-8.1],[-2.3,4.3]])
sum(sum(A**p))**(1/2)

11.58792474949678

In [7]:
norm(A)

11.58792474949678

### Eigendecomposition
Decomposing (breaking down) a matrix into a set of eigenvectors and eigenvalues.
* <b>Eigenvector</b> of a square matrix A is a nonzero vector v such that multiplication by A gives us back a scaled version of v. (Av = cv where c is that scalar)
* <b>Eigenvalue</b> actually ends up being that scalar (or c) corresponding to this eigenvector. It may also be important to note that left eigenvectors are possible so that v<sup>T</sup>A = cv<sup>T</sup>


In [37]:
A = np.array([[1,2,3],[3,2,1],[1,0,-1]])
eigen_value,eigen_vector = np.linalg.eig(A)

print("Eigenvectors (column wise):")
print(eigen_vector)

print("Eigenvalues:")
print(eigen_value)

Eigenvectors (column wise):
[[ 0.58428153  0.73595785  0.40824829]
 [ 0.80407569 -0.38198836 -0.81649658]
 [ 0.10989708 -0.55897311  0.40824829]]
Eigenvalues:
[ 4.31662479e+00 -2.31662479e+00  1.93041509e-17]


In [47]:
print("The matrix A multiplied by the eigenvector should equal the eigenvalue * eigenvector")
i = 1
print(f"A*v = {A.dot(eigen_vector[:,i])}")
print(f"c*v = {eigen_value[i]*eigen_vector[:,i]}")

The matrix A multiplied by the eigenvector should equal the eigenvalue * eigenvector
A*v = [-1.7049382   0.88492371  1.29493096]
c*v = [-1.7049382   0.88492371  1.29493096]


We can get the full <b>eigendecomposition</b> by concatenating all eigenvectors of a matrix column-wise and then putting all the corresponding eigenvalues in a vector.

If v is an eigenvector of A, then that means so is any rescaled vector cv, but cv still has the same eigenvalue. For this reason, usually you would only look for the unit eigenvectors (i.e. a vector with a unit norm ||x||<sub>2</sub> = 1). 

To make a unit eigenvector/vector you divide each element of vector v by the L<sup>2</sup> norm. Seen below.

In [47]:
v = np.array([2.5,-4.8,1.2])
print(f"Norm of vector v is: {norm(v)}")
print(f"So now we can divide vector v by the Norm {v/norm(v)}")
print(f"Now we can check that this is in fact a unit vector by taking the norm of this new vector: {norm(v/norm(v))}")
print(f"We know this is a unit vector since it is equivalent to 1")

Norm of vector v is: 5.543464620614079
So now we can divide vector v by the Norm [ 0.4509815  -0.86588448  0.21647112]
Now we can check that this is in fact a unit vector by taking the norm of this new vector: 1.0
We know this is a unit vector since it is equivalent to 1


Eigendecomposition can be expressed with the following formula:
A = V diag(c) V<sup>-1</sup>

In [56]:
eigen_vector.dot((np.diag(eigen_value))).dot(np.linalg.inv(eigen_vector))

array([[ 1.00000000e+00,  2.00000000e+00,  3.00000000e+00],
       [ 3.00000000e+00,  2.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  1.07568059e-16, -1.00000000e+00]])